### ISSUE TITLE
game version 1.19.4 support？

### ISSUE THREAD

**Issue by 8MiYile** [JustAHuman-xD/SlimefunToEMI#16]
why this update is support 1.19.3
isn't support 1.19.4?

**Comment by JustAHuman-xD** [comment]
The update is for 1.19.4?

**Comment by JustAHuman-xD** [comment]
> why this update is support 1.19.3
> 
> isn't support 1.19.4?

@8MiYile If you are referring to the beta, it is for 1.19.4, not 1.19.3
