### ISSUE TITLE
for rewrite

### ISSUE THREAD

**Issue by shixinzia** [JustAHuman-xD/SlimefunToEMI#17]
I installed Slimefun Server Essentials to export slimefun and its attached data and migrate it to slimefun essentials. Only the recipe of slimefun ontology can be displayed in the game, but the attached recipe cannot be displayed. It has been configured in mod menu.

**Comment by JustAHuman-xD** [comment]
So Slimefun Server Essentials is not quite ready to properly export addons separated from slimefun, I am nearing finishing it but it isn't finished. That's why the Re-Write does not have any addons bundled with it.

**Comment by JustAHuman-xD** [comment]
If you want to supply the exported .json files I can take a look at how they need to be edited to work properly if you want?

**Comment by JustAHuman-xD** [comment]
Once I have finished Slimefun Server Essential's update I will properly release both it & the tutorial for exporting

**Comment by shixinzia** [comment]
[slimefun.zip](https://github.com/JustAHuman-xD/SlimefunEssentials/files/11239847/slimefun.zip)
Exported json
All addon installed on my server.

**Comment by JustAHuman-xD** [comment]
What recipe viewer mod are you using?

**Comment by shixinzia** [comment]
jei. Emi cannot display slimefun recipes.

**Comment by JustAHuman-xD** [comment]
Can you attach a log of that? It should work with EMI

**Comment by shixinzia** [comment]
[2023-04-15-3.log.gz](https://github.com/JustAHuman-xD/SlimefunEssentials/files/11240952/2023-04-15-3.log.gz)

**Comment by shixinzia** [comment]
EMI logs

**Comment by shixinzia** [comment]
[2023-04-15-4.log.gz](https://github.com/JustAHuman-xD/SlimefunEssentials/files/11240956/2023-04-15-4.log.gz)
jei logs

**Comment by JustAHuman-xD** [comment]
Interesting, I will take a look! thank you

**Comment by JustAHuman-xD** [comment]
Judging by the logs you haven't configured enabled Addons in the mod correctly

**Comment by shixinzia** [comment]
?

**Comment by shixinzia** [comment]
How to enable it correctly

**Comment by JustAHuman-xD** [comment]
In the config (I would recommend installing cloth config for the built in gui). Add every file name to the list of enabled Addons. Capitalization doesn't matter

**Comment by shixinzia** [comment]
I've tried, and it's no use.

**Comment by JustAHuman-xD** [comment]
Using the json files you gave me I was able to do it, and it worked properly. Once I have the full tutorial up you can try following that.

**Comment by shixinzia** [comment]
Can you give a complete tutorial?

**Comment by shixinzia** [comment]
I configure it through mod menu.

**Comment by JustAHuman-xD** [comment]
Can you provide a screenshot of your addon list?
