### ISSUE TITLE
[Solved] Mod not working with EMI

### ISSUE THREAD

**Issue by WaterWolf5918** [JustAHuman-xD/SlimefunToEMI#18]
# No Slimefun items are displayed in EM. 
I can however see recipes, if i check recipes for charcoal i can see recipes from slimefun.

## SlimefunEssentials Config
[slimefun_essentials.txt](https://github.com/JustAHuman-xD/SlimefunEssentials/files/11579359/slimefun_essentials.txt)
> I had to change the file type to txt for it to be uploaded

## Minecraft Log
[latest.log](https://github.com/JustAHuman-xD/SlimefunEssentials/files/11579356/latest.log)

## Mod list
- Cloth Config VIO
- EMI
- Fabric API
- Mod Menu
- Slimefun Essentials

## Item list screenshot 
![image](https://github.com/JustAHuman-xD/SlimefunEssentials/assets/87424826/60296fcd-4649-4c5a-8a2c-e5ad9f474124)

## Recipe screenshot
![image](https://github.com/JustAHuman-xD/SlimefunEssentials/assets/87424826/d140ede2-618e-42ed-b060-5c58ffb4e4e7)

**Comment by JustAHuman-xD** [comment]
Known issue! I have already committed a fix I'm just waiting till I finish some other tweaks before I release the next beta version. However on discord I can send you a build it the fix applied.

**Comment by WaterWolf5918** [comment]
I built a version from the github and it works Thanks.
