### ISSUE TITLE
Add Support for Just Enough Calculation

### ISSUE THREAD

**Issue by 54M44R** [JustAHuman-xD/SlimefunToEMI#23]
Just Enough Calculation is a mod that assists in calculating the materials needed for a recipe. It is very useful when working with large and / or complex recipes.

The mod also supports placeholders, which are meant as a way to signify more abstract things, such as a multiblock structure. Say you have a multiblock X, which requires blocks A, B, and C. You can create a placeholder, called X, and use it as the "output" portion of a recipe. In essence, this also assists with builds as well.

Currently though, almost all items from SlimefunEssentials are being registered as Placeholders. 

Example with recipe for 5 reinforced ingots:

![image](https://github.com/JustAHuman-xD/SlimefunEssentials/assets/26176694/da348c98-f335-4bc0-b246-501f308deaa6)

With their names being:

![image](https://github.com/JustAHuman-xD/SlimefunEssentials/assets/26176694/72ca5980-3868-466d-9722-41241e7dad18)

The naming scheme suggests its related to the `SlimefunItemStack()` method. For clarity, they are not all considered `Damascus Steel`

It seems that items without a registered recipe function normally:

![image](https://github.com/JustAHuman-xD/SlimefunEssentials/assets/26176694/6cf7ab22-fe35-4bdd-b602-4df302a1fcfa)

The electric smeltery does not have a registered recipe from SlimefunEssentials, and thus is not considered a Placeholder by JEC.

I am unsure as to what leads JEC to assume SlimefunEssentials items as Placeholder items. Assuming the cause is identified and fixed, this would make SlimefunEssentials and JEC compatiable.

**Comment by JustAHuman-xD** [comment]
I can add it to my to do list, no guarantee as to when I'll look into it

**Comment by JustAHuman-xD** [comment]
@54M44R could you send the logs too?

**Comment by 54M44R** [comment]
This comment is to serve as a record that commit #037908e has fully implemented support for JEC.

![image](https://github.com/JustAHuman-xD/SlimefunEssentials/assets/26176694/16f43585-7be1-4868-9367-aca722d93d82)
