### ISSUE TITLE
mod are not support for 1.20.1?

### ISSUE THREAD

**Issue by fxcthe** [JustAHuman-xD/SlimefunToEMI#27]
this mod not support 1.20.1?

**Comment by JustAHuman-xD** [comment]
The latest version does not no

**Comment by JustAHuman-xD** [comment]
As much as I would love to back port I've decided to just close these as I don't have the time and when I do, I frankly would rather work on new features and fixes, than back porting the mod. If anyone does unofficially then great but otherwise I do not plan on back porting. Sorry!
