### ISSUE TITLE
[Suggestion] Want Support REI Mod and automatic get slimefun's addons list

### ISSUE THREAD

**Issue by 8MiYile** [JustAHuman-xD/SlimefunToEMI#8]
want support REI Mod can display slimefun's crafting

**Comment by JustAHuman-xD** [comment]
This is already planned and will be coming after the next big update.

**Comment by 8MiYile** [comment]
and
i'll help you auto get addons list
just this mod in server chunk loaded
auto input command /sf addon list
can get addons list
![image](https://user-images.githubusercontent.com/25455400/213976451-60c95e3b-f32c-4233-a387-2ac97440ee61.png)

**Comment by JustAHuman-xD** [comment]
It's ok, I already know all the Addons, I've even made one lol

**Comment by 8MiYile** [comment]
@JustAHuman-xD 
it's just auto on/off display addon's recipes list

**Comment by JustAHuman-xD** [comment]
A way to automate it per server? If so I already have a plan for it in a later update.

**Comment by 8MiYile** [comment]
@JustAHuman-xD 
In communication with Slimefun development team
See if they allow players to access the extension list
If this is allowed, you just have to do it after the player has joined the server.
Send a request to get the list of Addons
Of course, it is possible to get the recipe (but the amount of data transferred will become very high, or just get the list of Addons)

**Comment by 8MiYile** [comment]
@JustAHuman-xD 
and you can try
`/sf version`
maybe can get addons list

**Comment by 8MiYile** [comment]
https://github.com/Slimefun/Slimefun4/pull/3750
https://github.com/StarWishsama/Slimefun4/pull/662

**Comment by JustAHuman-xD** [comment]
If you look at SlimefunServerEssentials and the rewrite branch of this (SlimefunEssentials), I have REI support almost done, auto Addons are done

**Comment by 8MiYile** [comment]
maybe support REI mod
i can close this
